version: "2"
services:
  kafka-producer:
    image: kafkaapps/kafka-producer:latest
    build: 
      context: ./kafka-producer
      dockerfile: dockerfile
    hostname: kafka-producer
    container_name: kafka-producer
    ports:
      - "8080:8080"
    environment:
      - KAFKA_TOPIC=InventoryUpdates
      - environment=Development
  kafka-consumer:
    image: kafkaapps/kafka-consumer:latest
    build: 
      context: ./kafka-consumer
      dockerfile: dockerfile
    hostname: kafka-consumer
    container_name: kafka-consumer
    environment:
      - KAFKA_TOPIC=InventoryUpdates
